# Consts
SECNER_LABEL2ID = {
    'O': 0,
    'B-TIME': 1,
    'I-TIME': 2,
    'B-LOC': 3,
    'B-SECTEAM': 4,
    'I-SECTEAM': 5,
    'B-TOOL': 6,
    'B-IDTY': 7,
    'I-IDTY': 8,
    'B-MAL': 9,
    'B-APT': 10,
    'I-APT': 11,
    'I-TOOL': 12,
    'B-VULNAME': 13,
    'B-VULID': 14,
    'I-LOC': 15,
    'B-ENCR': 16,
    'B-FILE': 17,
    'B-SHA2': 18,
    'B-URL': 19,
    'B-IP': 20,
    'PROT': 21,
    'B-ACT': 22,
    'I-ACT': 23,
    'B-MD5': 24,
    'I-FILE': 25,
    'B-DOM': 26,
    'I-MAL': 27,
    'B-OS': 28,
    'B-SHA1': 29,
    'I-URL': 30,
    'I-IP': 31,
    'I-SHA2': 32,
    'I-OS': 33,
    'B-PROT': 34,
    'I-VULNAME': 35,
    'I-PROT': 36,
    'B-EMAIL': 37,
    'I-EMAIL': 38,
    'I-ENCR': 39
}

# Taken from: https://huggingface.co/CyberPeace-Institute/SecureBERT-NER
SECNER_LABEL2NAME = {
    'APT': 'Threat Participants',
    'SECTEAM': 'Security team',
    'IDTY': 'Authentication Identity',
    'OS': 'Operating system',
    'EMAIL': 'Malicious mailbox',
    'LOC': 'Location',
    'TIME': 'Time',
    'IP': 'IP address',
    'DOM': 'Domain',
    'URL': 'URL',
    'PROT': 'Protocol',
    'FILE': 'File sample',
    'TOOL': 'Tool',
    'MD5': 'Hash value',
    'SHA1': 'Hash value',
    'SHA2': 'Hash value',
    'MAL': 'Malware',
    'ENCR': 'Encryption algorithm',
    'VULNAME': 'Vulnerability name',
    'VULID': 'Vulnerability number',
    'ACT': 'Attack action',
    'O': 'Other',
}