FROM python:3.10 as base

WORKDIR /app

COPY requirements.txt ./

RUN --mount=type=cache,target=/root/.cache pip install -r requirements.txt

RUN mkdir -p models
COPY models models

RUN mkdir -p onnx
COPY build/onnx onnx

FROM base as build

COPY src .
COPY src/app/streamlit.py .

EXPOSE 8501

ENV TQDM_DISABLE 1

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "streamlit.py", "--server.port=8501", "--server.address=0.0.0.0"]
